<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConfigSeeder extends Seeder
{
    public function run()
    {
        $configs = [
            // إعدادات العقارات
            [
                'key' => 'property.require_approval',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'يتطلب موافقة المسؤول قبل إدراج العقارات',
                'group' => 'property',
                'is_public' => false,
            ],
            [
                'key' => 'property.max_photos',
                'value' => '12',
                'type' => 'number',
                'description' => 'الحد الأقصى لعدد الصور لكل عقار',
                'group' => 'property',
                'is_public' => true,
            ],
            [
                'key' => 'property.allow_edit_after_post',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'السماح للمستخدمين بتعديل العقارات بعد النشر',
                'group' => 'property',
                'is_public' => true,
            ],
            [
                'key' => 'property.auto_archive_days',
                'value' => '90',
                'type' => 'number',
                'description' => 'عدد الأيام بعدها يتم أرشفة الإعلانات غير النشطة تلقائياً',
                'group' => 'property',
                'is_public' => false,
            ],

            // إعدادات الاشتراكات
            [
                'key' => 'subscription.allow_change_before_end',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'السماح بتغيير الخطة قبل انتهاء الصلاحية',
                'group' => 'subscription',
                'is_public' => false,
            ],
            [
                'key' => 'subscription.refund_policy',
                'value' => 'days',
                'type' => 'enum',
                'options' => json_encode(['days', 'cash', 'none']),
                'description' => 'طريقة الاسترداد عند الإلغاء المبكر',
                'group' => 'subscription',
                'is_public' => true,
            ],
            [
                'key' => 'subscription.default_plan_id',
                'value' => '1',
                'type' => 'number',
                'description' => 'الخطة الافتراضية للمستخدمين الجدد',
                'group' => 'subscription',
                'is_public' => false,
            ],
            [
                'key' => 'subscription.trial_days',
                'value' => '7',
                'type' => 'number',
                'description' => 'عدد أيام التجربة قبل طلب الدفع',
                'group' => 'subscription',
                'is_public' => true,
            ],

            // إعدادات الإشعارات
            [
                'key' => 'notifications.email_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'إرسال إشعارات البريد الإلكتروني',
                'group' => 'notifications',
                'is_public' => false,
            ],
            [
                'key' => 'notifications.sms_enabled',
                'value' => 'false',
                'type' => 'boolean',
                'description' => 'إرسال إشعارات الرسائل النصية',
                'group' => 'notifications',
                'is_public' => false,
            ],
            [
                'key' => 'notifications.new_property_alerts',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'إعلام المستخدمين بعقارات جديدة تتناسب مع اهتماماتهم',
                'group' => 'notifications',
                'is_public' => true,
            ],

            // إعدادات الموقع/التطبيق
            [
                'key' => 'app.name',
                'value' => 'تطبيق العقارات الخاص بي',
                'type' => 'text',
                'description' => 'اسم التطبيق (العلامة التجارية)',
                'group' => 'app',
                'is_public' => true,
            ],
            [
                'key' => 'app.url',
                'value' => 'https://yourdomain.com',
                'type' => 'link',
                'description' => 'رابط الموقع الرئيسي',
                'group' => 'app',
                'is_public' => true,
            ],
            [
                'key' => 'app.support_email',
                'value' => 'support@yourdomain.com',
                'type' => 'text',
                'description' => 'بريد الدعم الفني',
                'group' => 'app',
                'is_public' => true,
            ],
            [
                'key' => 'app.maintenance_mode',
                'value' => 'false',
                'type' => 'boolean',
                'description' => 'عرض صفحة الصيانة',
                'group' => 'app',
                'is_public' => true,
            ],
            [
                'key' => 'app.default_language',
                'value' => 'en',
                'type' => 'enum',
                'options' => json_encode(['en', 'ar']),
                'description' => 'اللغة الافتراضية للتطبيق',
                'group' => 'app',
                'is_public' => true,
            ],
            [
                'key' => 'app.logo_url',
                'value' => '/images/logo.png',
                'type' => 'link',
                'description' => 'رابط شعار التطبيق',
                'group' => 'app',
                'is_public' => true,
            ],

            // إعدادات الأمان والخصوصية
            [
                'key' => 'security.enable_recaptcha',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'تفعيل Google reCAPTCHA في النماذج',
                'group' => 'security',
                'is_public' => false,
            ],
            [
                'key' => 'security.failed_login_limit',
                'value' => '5',
                'type' => 'number',
                'description' => 'الحد الأقصى لمحاولات تسجيل الدخول الفاشلة قبل الحظر',
                'group' => 'security',
                'is_public' => false,
            ],
            [
                'key' => 'security.block_time_minutes',
                'value' => '30',
                'type' => 'number',
                'description' => 'مدة الحظر بعد الوصول للحد الأقصى لمحاولات تسجيل الدخول الفاشلة',
                'group' => 'security',
                'is_public' => false,
            ],
            [
                'key' => 'privacy.show_email_in_listing',
                'value' => 'false',
                'type' => 'boolean',
                'description' => 'عرض بريد المستخدم في الإعلانات العامة',
                'group' => 'privacy',
                'is_public' => true,
            ],
            [
                'key' => 'app.logo_dark_url',
                'value' => '',
                'type' => 'link',
                'description' => 'رابط شعار الوضع المظلم',
                'group' => 'app',
                'is_public' => true,
            ],
            [
                'key' => 'landing.catchy_phrase_primary',
                'value' => 'ابحث عن عقارك المثالي، بسرعة وسهولة!',
                'type' => 'text',
                'description' => 'العبارة الجذابة الرئيسية في الصفحة الرئيسية',
                'group' => 'landing',
                'is_public' => true,
            ],
            [
                'key' => 'landing.catchy_phrase_secondary',
                'value' => 'نساعدك في الشراء والبيع والتأجير بثقة.',
                'type' => 'text',
                'description' => 'العبارة الجذابة الثانوية في الصفحة الرئيسية',
                'group' => 'landing',
                'is_public' => true,
            ],
            [
                'key' => 'service.catchy_phrase_primary',
                'value' => 'هذه هي الخدمة',
                'type' => 'text',
                'description' => 'العبارة الجذابة الرئيسية المعروضة في قسم الخدمات',
                'group' => 'service',
                'is_public' => true,
            ],
            [
                'key' => 'service.catchy_phrase_secondary',
                'value' => 'خطط مرنة تناسب كل الميزانيات!',
                'type' => 'text',
                'description' => 'العبارة الجذابة الثانوية المعروضة في قسم الخدمات',
                'group' => 'service',
                'is_public' => true,
            ],
            [
                'key' => 'pricing.catchy_phrase_primary',
                'value' => 'هذه هي الأسعار',
                'type' => 'text',
                'description' => 'العبارة الجذابة الرئيسية المعروضة في قسم الأسعار',
                'group' => 'pricing',
                'is_public' => true,
            ],
            [
                'key' => 'pricing.catchy_phrase_secondary',
                'value' => 'خطط مرنة تناسب كل الميزانيات!',
                'type' => 'text',
                'description' => 'العبارة الجذابة الثانوية المعروضة في قسم الأسعار',
                'group' => 'pricing',
                'is_public' => true,
            ],
            [
                'key' => 'pricing.package_comperson',
                'value' => 'خطط مرنة تناسب كل الميزانيات!',
                'type' => 'text',
                'description' => 'عبارة مقارنة الباقات المعروضة في قسم الأسعار',
                'group' => 'pricing',
                'is_public' => true,
            ],
            [
                'key' => 'pricing.faq',
                'value' => 'خطط مرنة تناسب كل الميزانيات!',
                'type' => 'text',
                'description' => 'عبارة الأسئلة الشائعة المعروضة في قسم الأسعار',
                'group' => 'pricing',
                'is_public' => true,
            ],
            [
                'key' => 'cta.catchy_phrase_primary',
                'value' =>  "ابدأ رحلتك اليوم!",
                'type' => 'json',
                'description' => 'عبارات الحث على الإجراء الرئيسية المستخدمة عبر الصفحة الرئيسية',
                'group' => 'landing',
                'is_public' => true,
            ],
            [
                'key' => 'cta.catchy_phrase_secondary',
                'value' => "انضم إلى الآلاف من العملاء الراضين.",
                'type' => 'json',
                'description' => 'عبارات الحث على الإجراء الثانوية المستخدمة عبر الصفحة الرئيسية',
                'group' => 'landing',
                'is_public' => true,
            ],

            // من نحن
            [
                'key' => 'about.short',
                'value' => 'نحن منصة عقارية رائدة ملتزمون بالجودة والثقة.',
                'type' => 'textarea',
                'description' => 'وصف مختصر عن الشركة',
                'group' => 'about',
                'is_public' => true,
            ],
            [
                'key' => 'about.detailed',
                'value' => 'نحن منصة عقارية رائدة ملتزمون بالجودة والثقة.',
                'type' => 'textarea',
                'description' => 'وصف مفصل عن الشركة',
                'group' => 'about',
                'is_public' => true,
            ],
            [
                'key' => 'about.static_experiance',
                'value' =>  '+5',
                'type' => 'number',
                'description' => 'سنوات الخبرة',
                'group' => 'about',
                'is_public' => true,
            ],
            [
                'key' => 'about.vision',
                'value' =>  'أن نكون المنصة العقارية الأولى في المنطقة.',
                'type' => 'text',
                'description' => 'بيان الرؤية',
                'group' => 'about',
                'is_public' => true,
            ],
            [
                'key' => 'about.mission',
                'value' => 'تمكين المستخدمين بحلول عقارية موثوقة.',
                'type' => 'text',
                'description' => 'بيان المهمة',
                'group' => 'about',
                'is_public' => true,
            ],
            [
                'key' => 'about.values_intro',
                'value' => 'ربط الناس بالعقارات التي يحبونها.',
                'type' => 'text',
                'description' => 'جملة مختصرة عن القيم',
                'group' => 'about',
                'is_public' => true,
            ],
            [
                'key' => 'about.team_catchy_phrase',
                'value' => 'تعرف على الفريق الذي يقف وراء مهمتنا.',
                'type' => 'text',
                'description' => 'مقدمة قسم الفريق',
                'group' => 'about',
                'is_public' => true,
            ],

            // تذييل الصفحة والصفحات القانونية
            [
                'key' => 'footer.about_short_sentence',
                'value' => 'شريكك الموثوق في العقارات.',
                'type' => 'text',
                'description' => 'جملة قصيرة عن الشركة في التذييل',
                'group' => 'footer',
                'is_public' => true,
            ],
            [
                'key' => 'contact_info.email',
                'value' => 'contact@yourdomain.com',
                'type' => 'text',
                'description' => 'معلومات الاتصال في التذييل',
                'group' => 'footer',
                'is_public' => true,
            ],
            [
                'key' => 'contact_info.phone',
                'value' => '+1234567890',
                'type' => 'text',
                'description' => 'معلومات الاتصال في التذييل',
                'group' => 'footer',
                'is_public' => true,
            ],
            [
                'key' => 'contact_info.address',
                'value' => '123 شارع العقارات، العاصمة',
                'type' => 'text',
                'description' => 'معلومات الاتصال في التذييل',
                'group' => 'footer',
                'is_public' => true,
            ],
            [
                'key' => 'page.privacy',
                'value' => '/privacy-policy',
                'type' => 'textarea',
                'description' => 'محتوى صفحة سياسة الخصوصية',
                'group' => 'pages',
                'is_public' => false,
            ],
            [
                'key' => 'page.terms',
                'value' => '/terms-of-service',
                'type' => 'textarea',
                'description' => 'محتوى صفحة الشروط والأحكام',
                'group' => 'pages',
                'is_public' => false,
            ],
            [
                'key' => 'page.help',
                'value' => '/help',
                'type' => 'textarea',
                'description' => 'محتوى صفحة المساعدة/الدعم',
                'group' => 'pages',
                'is_public' => false,
            ],
            [
                'key' => 'page.faq',
                'value' => '/faq',
                'type' => 'textarea',
                'description' => 'محتوى صفحة الأسئلة الشائعة',
                'group' => 'pages',
                'is_public' => false,
            ],
        ];

        foreach ($configs as $config) {
            DB::table('configs')->updateOrInsert(
                ['key' => $config['key']],
                $config
            );
        }
    }
}
